[package]
name = "ground-station"
version = "0.1.0"
edition = "2021"

[dependencies]
serialport = "4.6.1"
tungstenite = { version = "0.24.0", features = ["rustls-tls-native-roots"] }
serial2-tokio = "0.1.14"
tokio = { version = "1.44.0", features = ["full"] }
